// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BackendAPI.Models;

public partial class MasterDBContext : DbContext
{
    public MasterDBContext(DbContextOptions<MasterDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MsStorageLocation> MsStorageLocations { get; set; }

    public virtual DbSet<MsUser> MsUsers { get; set; }

    public virtual DbSet<TrBpkb> TrBpkbs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MsStorageLocation>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__ms_stora__771831EA906050C2");

            entity.ToTable("ms_storage_location");

            entity.Property(e => e.LocationId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("location_id");
            entity.Property(e => e.LocationName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("location_name");
        });

        modelBuilder.Entity<MsUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ms_user__3213E83FF7D87AD8");

            entity.ToTable("ms_user");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Isactive).HasColumnName("isactive");
            entity.Property(e => e.Passwords)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("passwords");
            entity.Property(e => e.UserNames)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("user_names");
        });

        modelBuilder.Entity<TrBpkb>(entity =>
        {
            entity.HasKey(e => e.Agreementnumber).HasName("PK__tr_bpkb__EDBFB661DF2A7D97");

            entity.ToTable("tr_bpkb");

            entity.Property(e => e.Agreementnumber)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("agreementnumber");
            entity.Property(e => e.BpkbDate)
                .HasColumnType("datetime")
                .HasColumnName("bpkb_date");
            entity.Property(e => e.BpkbDateIn)
                .HasColumnType("datetime")
                .HasColumnName("bpkb_date_in");
            entity.Property(e => e.BpkbNo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("bpkb_no");
            entity.Property(e => e.BranchId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("branch_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedOn)
                .HasColumnType("datetime")
                .HasColumnName("created_on");
            entity.Property(e => e.FakturDate)
                .HasColumnType("datetime")
                .HasColumnName("faktur_date");
            entity.Property(e => e.FakturNo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("faktur_no");
            entity.Property(e => e.LastUpdatedBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("last_updated_by");
            entity.Property(e => e.LastUpdatedOn)
                .HasColumnType("datetime")
                .HasColumnName("last_updated_on");
            entity.Property(e => e.LocationId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("location_id");
            entity.Property(e => e.PoliceNo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("police_no");

            entity.HasOne(d => d.Location).WithMany(p => p.TrBpkbs)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK__tr_bpkb__locatio__2A4B4B5E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}