// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models;

public partial class MsStorageLocation
{
    public string LocationId { get; set; }

    public string LocationName { get; set; }

    public virtual ICollection<TrBpkb> TrBpkbs { get; set; } = new List<TrBpkb>();
}